#!/bin/sh

set -e

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

script/bootstrap

xcodebuild \
  -workspace Example/UITextView+UIControl.xcworkspace \
  -scheme UITextView+UIControl \
  -sdk iphonesimulator clean test \
  | bundle exec xcpretty --color
