#!/bin/sh

set -e

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

script/bootstrap

vendor/xctool/xctool.sh -workspace Example/UITextView+UIControl.xcworkspace -scheme UITextView+UIControl ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator clean test
